liqd/a4-product

webpack.config.js
fixes #3
see https://github.com/liqd/a4-meinberlin/pull/632 for reference
=> fix IE11 incompatibility with react

liqd_product/apps/partners/templates/partner_base.html, liqd_product/apps/partners/templates/partner_landing_page.html, liqd_product/apps/partners/urls.py, liqd_product/apps/partners/views.py, liqd_product/apps/users/templates/liqd_product_users/indicator.html, liqd_product/assets/scss/_layout.scss, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_header.scss, liqd_product/assets/scss/components/nav.scss, liqd_product/assets/scss/components/navi.scss, liqd_product/assets/scss/style.scss, liqd_product/config/urls.py, liqd_product/templates/base.html, liqd_product/templates/footer.html, liqd_product/templates/header.html
=> 2017 07 pv navs

liqd_product/apps/partners/templates/partner_landing_page.html, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_hero-unit.scss, liqd_product/assets/scss/style.scss
=> style hero unit

liqd_product/assets/scss/_base.scss, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/style.scss
based on #11 
Add type sizes and basic heading styles and make links bold instead of underlined
=> typography

liqd_product/apps/partners/templates/partner_landing_page.html, liqd_product/apps/partners/views.py, liqd_product/assets/scss/_base.scss, liqd_product/assets/scss/components/_aside.scss, liqd_product/assets/scss/components/_headings.scss, liqd_product/assets/scss/components/_stats.scss, liqd_product/assets/scss/style.scss, liqd_product/config/settings/base.py, liqd_product/templates/base.html
builds on #14
depends on https://github.com/liqd/a4-meinberlin/pull/655
=> style partner aside

liqd_product/assets/scss/components/_footer.scss, liqd_product/templates/footer.html
- Black background
- White font
- Deleted links to Facebook, Twitter and Flickr
- "Powered by Adhocracy4" is now centered.
=> New layout for the landing page footer

liqd_product/apps/users/templates/liqd_product_users/indicator.html
=> Fix menu on mobile

liqd_product/apps/partners/urlresolvers.py
Not importing depricated urlresolver.
This resulted on the resolve function of urlresolver not being patched.
=> Fix urlresolver

Makefile
see https://github.com/liqd/a4-meinberlin/pull/946
=> add webpack make target for production

tests/factories.py
=> Generate unique usernames and passwords

package.json
=> fix(package): update webpack to version 3.9.1

liqd_product/apps/cms/pages/templates/liqd_product_cms_pages/home_page.html, liqd_product/assets/scss/components/_footer.scss
Refactor homepage html in order to get a styling baseline. Additional styling (underlined headings, hero image, …) should be done separately.
=> basic homepage styling

liqd_product/assets/scss/_form.scss, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_button.scss, liqd_product/assets/scss/components/_comments.scss, liqd_product/assets/scss/components/_poll.scss, liqd_product/assets/scss/components/_tabs.scss, liqd_product/assets/scss/style.scss
Note that most of these changes are practically monkey-patches because they rely on knowledge of meinberlin CSS internals. In the long term this should be refactored, probably by duplicating and merging in the code from meinberlin.
=> more styling

liqd_product/apps/users/adapters.py, liqd_product/templates/account/email_confirm.html
copy of https://github.com/liqd/a4-meinberlin/pull/1072
=> redirect on registration

liqd_product/apps/embed/urls.py, liqd_product/apps/embed/views.py, liqd_product/config/urls.py, liqd_product/templates/meinberlin_embed/embed.html, webpack.config.js
Set the partner for embedded views in django
Furthermore it fixes the required js which was not build by webpack and overwrites the embed template which contained meinBerlin related strings
fixes #113 
The styling of the embed envelop could be improved for beteiligung.in
=> Fix embedding

liqd_product/apps/users/templates/liqd_product_users/indicator.html, liqd_product/assets/scss/components/_button.scss, liqd_product/assets/scss/components/_main_header.scss, liqd_product/assets/scss/components/_userindicator.scss, liqd_product/assets/scss/style.scss, liqd_product/templates/header.html
- very very basic userindicator styling (mainly colours)
- still have to change the whole menu-thingy and spacing
=> 2017 12 ka user indicator

liqd_product/apps/partners/templates/partner_landing_page.html, liqd_product/assets/scss/components/_action.scss, liqd_product/assets/scss/components/_aside.scss, liqd_product/assets/scss/components/_partner.scss, liqd_product/assets/scss/components/_tile.scss
fixes #283, #284, #286 
fixes bits of #285, but this has to be further discussed and tested
=> Ka 2018 02 partner landing page

liqd_product/apps/contrib/templatetags/marked_tags.py, liqd_product/apps/partners/templates/partner_landing_page.html, liqd_product/assets/scss/components/_marked.scss
=> add marked tag to use marked class in multiple (translated) words

renovate.json
=> remove last comma

Makefile, README.md, liqd_product/fixtures/orga-dev.json, liqd_product/fixtures/partner-dev.json, liqd_product/fixtures/site-dev.json, liqd_product/fixtures/users-dev.json
I added an initiator and a partner_admin. Might help when we actually fix these roles (user story).
=> Ka 2018 05 add fixtures

liqd_product/templates/header.html, locale/de/LC_MESSAGES/django.po
changed 'FAQ' to 'Information' with Moritz go ahead
=> changed text on tab fixes#393

liqd_product/apps/contrib/sitemaps/product_partners_sitemap.py, liqd_product/apps/contrib/sitemaps/product_projects_sitemap.py, liqd_product/apps/contrib/sitemaps/static_sitemap.py, liqd_product/apps/partners/models.py, liqd_product/config/settings/base.py, liqd_product/config/settings/dev.py, liqd_product/config/urls.py, liqd_product/templates/robots.txt, requirements/base.txt
This implements sitemaps for partners and all projects (if they are public etc.)
=> add robots.txt and sitemap.xml

liqd_product/templates/meinberlin_projects/emails/invite_participant.de.email, liqd_product/templates/meinberlin_projects/emails/invite_participant.en.email, requirements/base.txt
It was just a typo. Also update some dependencies
Fixes #471
=> Fix invitation mails

.eslintrc, package.json
Copy pasted `.eslintrc` from mB, for some reason this fixes the test error :)
=> eslintrc: Add jsx-a11y

liqd_product/apps/projects/dashboard.py, liqd_product/apps/projects/forms.py, locale/de/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/django.po
=> Mn 2019 03 add translations

liqd_product/config/settings/base.py
=> wagtail: use legacy rt edotor to make streamfield blocks editable again

liqd_product/apps/actions/assets/timestamps.js, liqd_product/config/settings/base.py, liqd_product/templates/a4reports/emails/report_creator.en.email, liqd_product/templates/a4reports/emails/report_moderator.en.email, liqd_product/templates/header.html
translations currently working with browser language 
Emails not working but we can separate email translations and adding switch translations into 2 tasks
=> #1922 [bet.in] English version of Beteiligung.in step 1

locale/de/LC_MESSAGES/djangojs.po
=> locale/en: remove fuzzy label and make translations work again

liqd_product/templates/a4dashboard/base_dashboard.html, liqd_product/templates/header_dashboard.html
=> [apps/dashboard] add language switch dashboard header

liqd_product/assets/scss/components/_main_header.scss
adding position right for mobile view
=> lang switch: position on mobile

locale/de/LC_MESSAGES/django.po
=> header: missing translation in header added

Makefile, apps/activities/phases.py, apps/budgeting/phases.py, apps/dashboard/blueprints.py, apps/documents/phases.py, apps/ideas/phases.py, apps/mapideas/phases.py, apps/polls/phases.py, liqd_product/templates/a4dashboard/base_project_list.html, liqd_product/templates/a4dashboard/blueprint_list.html, locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/en_GB/LC_MESSAGES/django.po, locale/en_GB/LC_MESSAGES/djangojs.po
=> blueprint description: updating wording for descriptions of blueprints

.eslintrc, apps/contrib/static/js/ajax_modal.js, apps/contrib/static/js/unload_warning.js, liqd_product/assets/js/app.js, liqd_product/assets/js/embed.js, liqd_product/assets/js/map-address.js, liqd_product/assets/js/popover.js, liqd_product/assets/js/popup-close.js, requirements/base.txt
Which better detects webpack provided global variables.
=> ci: Use mB eslint config

apps/contrib/mixins.py, apps/projects/templates/a4_candy_projects/includes/project_list_tile.html, apps/projects/views.py, package.json, requirements/base.txt
- fixes when having a modulecluster with one module in the future the right module is displayed (same as this: https://github.com/liqd/a4-meinberlin/pull/2414)
- fixes https://github.com/liqd/a4-meinberlin/issues/2403
depends on: https://github.com/liqd/adhocracy4/pull/361
=> Bugfixes and updates from A4

apps/cms/contacts/templates/a4_candy_cms_contacts/form_field.html, apps/cms/contacts/templates/a4_candy_cms_contacts/form_page.html, apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_background_cta_block.html, apps/cms/pages/templates/a4_candy_cms_pages/home_page.html, apps/contrib/templates/a4_candy_contrib/component_library.html, liqd_product/assets/scss/_form.scss, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_blocks.scss, liqd_product/assets/scss/components/_button.scss, liqd_product/assets/scss/components/_contact_form.scss, liqd_product/assets/scss/components/_style_guide.scss
I have changed the border radius on the buttons because it looked weird with the form
=> Pm 2019 07 contact form

apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_background_cta_block.html, apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_cta_block.html, apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_img_cta_block.html, apps/cms/pages/templates/a4_candy_cms_pages/home_page.html, apps/contrib/templates/a4_candy_contrib/component_library.html, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_blocks.scss, liqd_product/assets/scss/components/_style_guide.scss
final tweaks to make everything look like designs for review. I will come in early on Tuesday so if anything is super weird i'll have a couple hours to sort it out :)
=> Pm 2019 07 homepage tidy

liqd_product/assets/scss/_base.scss, liqd_product/assets/scss/_fonts.scss, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_dropdown.scss, liqd_product/assets/scss/components/_tile.scss
=> Pm 2019 07 font sizes

apps/cms/contacts/templates/a4_candy_cms_contacts/includes/form.html, apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_cta_block.html, apps/cms/pages/templates/a4_candy_cms_pages/blocks/col_img_cta_block.html, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_blocks.scss, liqd_product/assets/scss/components/_contact_form.scss, liqd_product/assets/scss/components/_homepage.scss, liqd_product/assets/scss/components/_style_guide.scss
I made this from a merged branch hence number of commits, I thought rebasing master into this would mean merged commits would be removed but apparently not?! 
fixes #844
=> Pm 2019 07 list block

liqd_product/assets/scss/_base.scss, liqd_product/assets/scss/_shame.scss, liqd_product/assets/scss/_variables.scss, liqd_product/assets/scss/components/_blocks.scss, liqd_product/assets/scss/components/_contact_form.scss, liqd_product/assets/scss/components/_footer.scss, liqd_product/assets/scss/components/_homepage.scss, liqd_product/assets/scss/components/_language_switch.scss, liqd_product/assets/scss/components/_participation-tile.scss, liqd_product/assets/scss/components/_timeline-carousel.scss, liqd_product/templates/base.html, liqd_product/templates/footer.html
Due to accidentally making this branch from previous one I worked on (breakpoints) and linting errors that were only picked up by travis the commits are a bit of a mess, i'm sorry! but the fixes should be sound!
fixes #852
fixes #865 
fixes #864
fixes #872
attempted to fix issues #855 but due to specificity issues both fixes failed the tests, will revisit
=> Pm 2019 08 issues

apps/cms/news/templates/a4_candy_cms_news/news_page.html, apps/cms/pages/templates/a4_candy_cms_pages/home_page.html, apps/cms/use_cases/templates/a4_candy_cms_use_cases/use_case_page.html, liqd_product/assets/scss/components/_cms.scss
fixes #880 and that smaller images didn't cover the whole width of the news and use-case detail pages.
=> Ka 2019 08 wagtail images

apps/cms/news/models.py, apps/contrib/templates/a4_candy_contrib/includes/pagination.html, apps/ideas/views.py, liqd_product/assets/scss/components/_pagination.scss
To test it makes sense to set the paginations to 2:
https://github.com/liqd/a4-product/blob/0014c968a1805347412840ed62471867c07a77ce/apps/cms/news/models.py#L37
https://github.com/liqd/a4-product/blob/0014c968a1805347412840ed62471867c07a77ce/apps/ideas/views.py#L58
=> styling/pagination: use new pagination

liqd_product/assets/scss/components/_main_header.scss
=> Pm 2019 08 a11y lang
